dist: xenial
language: python

matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"

install:
  - pip install -e .
  - pip install pytest pytest-cov codecov

script: pytest tests  --cov-report term --cov=app/test/

after_success: codecov
